<a href="https://colab.research.google.com/github/shubhammadane/NLP-Project-by-Shubham-Madane/blob/main/Bag_of_Words_by_Shubham_Madane.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer

# Create the dataframe
df = pd.DataFrame({'text': ['people watch campus', 'campus watch campus', 'people write comment', 'campus write comment']})

# Display the dataframe
print("DataFrame:")
print(df)
print()

DataFrame:
                   text
0   people watch campus
1   campus watch campus
2  people write comment
3  campus write comment



### Data Preparation

This section initializes the necessary libraries and creates a sample DataFrame containing text data. This DataFrame will be used to demonstrate the functionality of `CountVectorizer`.

In [15]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()


### Initializing CountVectorizer

Here, we initialize `CountVectorizer` from `sklearn.feature_extraction.text`. This object will be used to convert a collection of text documents to a matrix of token counts (Bag-of-Words representation).

In [16]:
bow = cv.fit_transform(df['text'])

# vocab
print(cv.vocabulary_)

print(bow[0].toarray())
print(bow[1].toarray())

{'people': 2, 'watch': 3, 'campus': 0, 'write': 4, 'comment': 1}
[[1 0 1 1 0]]
[[2 0 0 1 0]]


### Fitting and Transforming the Data

We use `cv.fit_transform()` to both learn the vocabulary from the text data in our DataFrame (`df['text']`) and transform it into a Bag-of-Words matrix (`bow`). We then print the learned vocabulary and the Bag-of-Words representation for the first two documents.

In [17]:
# Print the bag-of-words for first two documents
print("Bag-of-Words for document 0 (people watch campus):")
print(bow[0].toarray())
print()

print("Bag-of-Words for document 1 (campus watch campus):")
print(bow[1].toarray())
print()

print("Bag-of-Words for document 0 (people watch campus):")
print(bow[2].toarray())
print()

print("Bag-of-Words for document 1 (campus watch campus):")
print(bow[3].toarray())
print()

Bag-of-Words for document 0 (people watch campus):
[[1 0 1 1 0]]

Bag-of-Words for document 1 (campus watch campus):
[[2 0 0 1 0]]

Bag-of-Words for document 0 (people watch campus):
[[0 1 1 0 1]]

Bag-of-Words for document 1 (campus watch campus):
[[1 1 0 0 1]]



### Displaying Bag-of-Words for Documents

This section explicitly displays the Bag-of-Words representation for each of the documents in the DataFrame. Each row in the output array corresponds to a document, and the columns represent the count of each word in the vocabulary for that document.

In [18]:
cv.fit(df['text'])
cv.transform(["campusx watch and write comment of campusx"]).toarray()

array([[0, 1, 0, 1, 1]])

### Transforming New Text

Here, we demonstrate how to transform a new, unseen sentence using the vocabulary learned from the training data. `cv.fit(df['text'])` ensures that the `CountVectorizer` is fitted to the training data first, and then `cv.transform()` converts the new sentence into its Bag-of-Words representation based on that learned vocabulary.