<a href="https://colab.research.google.com/github/shubhammadane/NLP-Project-by-Shubham-Madane/blob/main/N_Gram_By_Shubham_Madane.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer

This cell imports necessary libraries for text processing. `numpy` is used for numerical operations, `pandas` for data manipulation (specifically DataFrames), and `CountVectorizer` from `sklearn.feature_extraction.text` is a crucial tool for converting text into a matrix of token counts (Bag of Words model).

In [3]:
# Create the dataframe
df = pd.DataFrame({'text': ['people watch campus', 'campus watch campus', 'people write comment', 'campus write comment']})

# Display the dataframe
print("DataFrame:")
print(df)

DataFrame:
                   text
0   people watch campus
1   campus watch campus
2  people write comment
3  campus write comment


This cell creates a pandas DataFrame named `df` with a single column, 'text'. This DataFrame will hold our sample text documents that we want to process. The `print` statements are used to display the structure and content of this DataFrame to verify its creation.

In [20]:
# Initialize CountVectorizer with Bi-gram (n-gram range of 2)
# ngram_range=(2,2) means only pairs of consecutive words
cv = CountVectorizer(ngram_range=(2, 2))

Here, we initialize the `CountVectorizer`. The `ngram_range=(2, 2)` parameter is critical, as it configures the vectorizer to consider only **bi-grams** (sequences of two consecutive words). This means instead of counting single words, it will count occurrences of word pairs like 'people watch' or 'watch campus'.

In [22]:
# Fit and transform the text data to Bi-gram matrix
bow = cv.fit_transform(df['text'])

This cell performs two main actions: `fit` and `transform`.
- `fit(df['text'])`: The vectorizer learns the vocabulary of bi-grams from our `df['text']` column. It identifies all unique bi-grams and assigns them an index.
- `transform(df['text'])`: It then converts the text documents into a numerical representation (a 'Bag of Words' matrix), where each row corresponds to a document and each column corresponds to a bi-gram from the learned vocabulary, with values indicating the count of that bi-gram in the document. The result is stored in `bow`.

In [23]:
# Get the vocabulary (Bi-gram features)
print("Bi-gram Vocabulary:")
print(cv.vocabulary_)

Bi-gram Vocabulary:
{'people watch': 2, 'watch campus': 4, 'campus watch': 0, 'people write': 3, 'write comment': 5, 'campus write': 1}


This cell prints the `cv.vocabulary_`. This attribute of the `CountVectorizer` object shows the learned vocabulary of bi-grams. It's a dictionary where keys are the bi-grams and values are their assigned integer indices. This mapping is essential for understanding how the text is numerically represented.

In [7]:
# Display Bi-gram matrix for each document
print("Bi-gram representation for each document:")
print("Document 0 (people watch campus):", bow[0].toarray())
print("Document 1 (campus watch campus):", bow[1].toarray())
print("Document 2 (people write comment):", bow[2].toarray())
print("Document 3 (campus write comment):", bow[3].toarray())

Bi-gram representation for each document:
Document 0 (people watch campus): [[0 0 1 0 1 0]]
Document 1 (campus watch campus): [[1 0 0 0 1 0]]
Document 2 (people write comment): [[0 0 0 1 0 1]]
Document 3 (campus write comment): [[0 1 0 0 0 1]]


This cell demonstrates the bi-gram representation for each individual document. `bow` is a sparse matrix, so `.toarray()` is used to convert it into a dense NumPy array for easier viewing. Each row of the output array corresponds to a document, and the columns represent the counts of the bi-grams as defined in the vocabulary. For example, `Document 0` has a count of 1 for 'people watch' and 'watch campus'.

In [8]:
# Show complete Bi-gram matrix
print("\nComplete Bi-gram matrix:")
print(bow.toarray())


Complete Bi-gram matrix:
[[0 0 1 0 1 0]
 [1 0 0 0 1 0]
 [0 0 0 1 0 1]
 [0 1 0 0 0 1]]


This cell prints the complete bi-gram matrix for all documents. It concatenates the individual document representations into a single matrix. Each row is a document, and each column is a bi-gram feature from the vocabulary, with the cell values indicating the frequency of that bi-gram in the document.

In [9]:
# Show feature names (Bi-grams)
print("\nBi-gram Features:")
print(cv.get_feature_names_out())


Bi-gram Features:
['campus watch' 'campus write' 'people watch' 'people write'
 'watch campus' 'write comment']


This cell displays the actual bi-gram features (the word pairs) that correspond to the columns in our bi-gram matrix. `cv.get_feature_names_out()` returns a list of these bi-grams in the order of their assigned indices, which helps in interpreting the numerical `bow` matrix.

In [10]:
# Transform new sentence using fitted vectorizer
new_text = cv.transform(['campus watch and write comment of campus']).toarray()
print("\nNew text 'campus watch and write comment of campus' Bi-gram representation:")
print(new_text)


New text 'campus watch and write comment of campus' Bi-gram representation:
[[1 0 0 0 0 1]]


Here, we use the *already fitted* `CountVectorizer` to `transform` a *new* sentence. This is important because the vectorizer will only look for the bi-grams it learned from the original training data. 'and' and 'of' are stop words and are not part of the bi-grams learned from the `df['text']`, so they are ignored. The output shows the bi-gram counts for this new sentence based on the existing vocabulary.

In [11]:
# Alternative: Explicitly fit then transform
cv.fit(df['text'])
result = cv.transform(['campus watch and write comment of campus']).toarray()
print("\nResult after explicit fit and transform:")
print(result)


Result after explicit fit and transform:
[[1 0 0 0 0 1]]


This cell demonstrates an alternative approach: explicitly calling `fit()` and then `transform()` on the same data. While `fit_transform()` is a convenience method that combines these two steps, showing them separately can sometimes be clearer. In this specific case, since `cv` was already fitted on `df['text']` in a previous step, calling `cv.fit(df['text'])` again doesn't change the vocabulary. The `transform()` then processes the new sentence based on this vocabulary. The result is identical to the previous cell because the vocabulary remained the same.